language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
script: 'bundle exec rake'
matrix:
  include:
  - rvm: 2.4.0
    before_install:
      - gem uninstall libxml-ruby
      - sudo apt-get install ruby-libxml
      - sudo apt-get install libxml2
      - gem update bundler

notifications:
  email:
    recipients:
      - jatesins@ncsu.edu
    on_failure: change
    on_success: never
